# Default values for ibm-ucd agent chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# UCD Version
version: "7.1.2.0"
# version: "7.1.1.2"

image:
  pullPolicy: Always
  secret: "entitledregistry-secret"
ucdLicense:
# Change license to true to indicate have read and agree to license agreements : http://ibm.biz/ucd-license
  accept: true
license:
# Change license to true to indicate you have read and agree to license agreements : http://ibm.biz/ucd-license
  accept: true

# Persistent storage for agent configuration files
persistence:
  enabled: true
  useDynamicProvisioning: true
  fsGroup: "1001"
#  fsGroup:
  
confVolume:
  name: "conf"
  existingClaimName: ""
  storageClassName: "ibmc-block-gold"
  # storageClassName: ""
  size: "20Gi"
  accessMode: "ReadWriteOnce"
  # accessMode: "ReadWriteMany"

# UCD Agent Relay URI 
# random:(http://relay1:20080,http://relay2:20080)
relayUri: ""

# UCD Agent Relay Codestation URL 
# random:(https://relay1:20081,https://relay2:20081)
codestationUrl: ""

# UCD Server URI
# random:(wss://ucd1.example.com:7919,wss://ucd2.example.com:7919)
# TODO: provide url/route which is accessible outside of node also!
serverUri: "wss://UCD-RELEASENAME-ibm-ucd-prod:7919"

# Secret holding keystore password
secret:
  name: ""

# Initial teams and types this agent will be assigned to.
# team1:type1,team2:type2
agentTeams: ""

# User specified PV containing utilities to be executed by the UCD agent
# userUtils.executablesPath can list multiple directories, comma separated
userUtils:
  existingClaimName: ""
  executablesPath: "."

resources:
  constraints: 
    enabled: true
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 200Mi


